ranks:
  # If a player has multiple permission, whichever rank is listed first here is shown.
  owner:
    permission: 'bungeelist.owner'
    format: '&8[&2Owner&8]&r'
  developer:
    permission: 'bungeelist.developer'
    format: '&8[&6Developer&8]&r'
  moderator:
    permission: 'bungeelist.moderator'
    format: '&8[&3Moderator&8]&r'
  helper:
    permission: 'bungeelist.helper'
    format: '&8[&eHelper&8]&r'

groups:
  arenas:
    - 'Arena1'
    - 'Arena2'
    - 'Arena3'
  lobbies:
    - 'lobby1'
    - 'lobby2'
    - 'lobby3'

blacklist:
  - 'secretserver'

formats:
  header: "&6&m---------&e&l Staff Online &6&m---------"
  # %name% returns the name of the server or group.
  # %rank% returns the player's rank format.
  # %player% returns the player's name.

  # The title of the group or server
  # %total_online% - Total amount of players online
  # %total_online_staff% - Total amount of staff online
  # %total_online_group% - Total amount of staff online in a group/server
  title: "  &e&l%name% (%total_online_group%/%total_online_staff%)\n"
  # The format for players in a server without a group
  server: "    %rank% &f%player%\n"
  # The format for players in a server in a group
  group: "    %rank% &f %player% &e(%name%)\n"
  # Set to "" if you don't want a divider between groups/servers
  divider: "\n"

messages:
  no-staff: '&c&lOh no! &cThere are no staff members online'
  invalid-argument: '&cThis command is not available you can use &l/staff (vanish/reload)'
  no-console: '&cOnly players can use this command'
  no-permission: '&cYou do not have permission to use this command.'
  reload: '&aSuccessfully reloaded the config file.'
  vanish:
    enabled: '&aYou will no longer be listed on the staff list'
    disabled: '&aYou can now be seen on the staff list'